stages:
  - build
  - deploy

build-worker:
  image: docker:latest
  stage: build
  tags:
    - data_workers
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - unset DOCKER_HOST
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      source VERSION
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        tag="$VERSION"
      else
        tag="$CI_COMMIT_REF_SLUG$VERSION"
      fi
    - echo "Running on branch '$CI_COMMIT_BRANCH' -- tag = '$tag'"
    - echo "CI_REGISTRY_IMAGE = $CI_REGISTRY_IMAGE"
    - echo "CI_REGISTRY = $CI_REGISTRY"
    - |
      docker build -f ./dockerfile --pull -t "$CI_REGISTRY/$CI_PROJECT_NAME:$tag" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAME:$tag"
  # Run this job in the development branch  (must have a dockerfile there)
  rules:
    - changes:
        - VERSION
      if: $CI_COMMIT_BRANCH == "main" ||
          $CI_COMMIT_BRANCH == "dev"  ||
          $CI_COMMIT_BRANCH == "devops"
      

deploy_app:
  stage: deploy
  image:
    name: ieferrari/ansible:11.0.0
  tags:
    - data_workers
  script:
    - source VERSION
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        echo "<<<< PRODUCTION DEPLOY >>>>"
        target_server="prod"
        tag="$VERSION"
        cat $ansible_credentials_yml >> .infra/.ansible/cred.yml
        mv .infra/.env_prd .env
        mv .infra/config_prd.yml config.yml
        mv docker-compose-prd.yml docker-compose.yml
        export FOLDER_NAME=$CI_PROJECT_NAME
      else
        echo "<<<< DEVELOPMENT DEPLOY >>>>"
        tag="$CI_COMMIT_REF_SLUG$VERSION"
        target_server="dev"
        cat $ansible_credentials_yml_dev >> .infra/.ansible/cred.yml
        mv .infra/.env_dev .env
        mv .infra/config_dev.yml config.yml
        mv docker-compose-dev.yml docker-compose.yml
        export FOLDER_NAME=$CI_PROJECT_NAME"_dev"
      fi
    - chmod +x  .infra/.ansible/inject_secrets.sh 
    - .infra/.ansible/inject_secrets.sh
    - sed -i "s/IMAGE_VERSION=0*/IMAGE_VERSION=\"$tag\"/" .env
    - export  ANSIBLE_CONFIG=$(pwd)/.infra/.ansible/ansible.cfg
    - ansible-playbook -i .infra/hosts .infra/.ansible/docker_remote_launch.yml --extra-vars "server_name=$target_server folder_name=$FOLDER_NAME"
  rules:
  - changes:
      - VERSION
    if: $CI_COMMIT_BRANCH == "main" || 
        $CI_COMMIT_BRANCH == "dev"  || 
        $CI_COMMIT_BRANCH == "devops"
