stages:
  - docker_build
  - deploy

docker-build:
  image: docker:latest
  stage: docker_build
  tags:
    - data_workers
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      source VERSION
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        tag=":$VERSION"
        echo "Running on default branch 'main': tag = $VERSION"
      else
        tag=":$CI_COMMIT_REF_SLUG$VERSION"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "CI_REGISTRY_IMAGE= $CI_REGISTRY_IMAGE"
    - echo "CI_REGISTRY=  $CI_REGISTRY"
    - |
      docker build --pull -f dockerfile -t "$CI_REGISTRY/gpu_reports$tag" .
    - docker push "$CI_REGISTRY/gpu_reports$tag"
  # Run this job in the development branch  (must have a dockerfile there)
  only:
    refs:
      - dev
      - main
      - devops
    changes:
      - VERSION
      - api/*
      - core/*
      - services/*
      - factories/*
      - dockerfile

deploy_app:
  stage: deploy
  image:
    name: ieferrari/ansible:latest
  tags:
    - data_workers
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "false"
    ANSIBLE_FORCE_COLOR: "true"
  before_script:
    - apt install rsync -y
  script:
    - |
      source VERSION
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        echo "<<<< PRODUCTION DEPLOY >>>>"
        export target_server="batman"
        tag="$VERSION"
        cat $ENV_FILE_PROD > .env
        sed -i "s/IMAGE_VERSION=0*/IMAGE_VERSION=\"$tag\"/" .env
        cat $credentials_yml >> ./.ansible/cred.yml
        export folder_name="gpu_reports"
      else
        echo "<<<< DEVELOPMENT DEPLOY >>>>"
        export target_server="batman"
        tag="$CI_COMMIT_REF_SLUG$VERSION"
        cat $ENV_FILE_DEV > .env
        sed -i "s/IMAGE_VERSION=0*/IMAGE_VERSION=\"$tag\"/" .env
        cat $credentials_yml >> ./.ansible/cred.yml
        export folder_name="gpu_reports_dev"
      fi
    - export  ANSIBLE_CONFIG=$(pwd)/.ansible/ansible.cfg
    - echo "------ Ansible deploy -------"
    - echo "project \:\ "$folder_name
    - echo "target server\:\ "$target_server
    - ansible-playbook -i .ansible/hosts .ansible/docker_remote_launch.yml sudo usermod -aG docker

  # Run this job in the dev branch
  only:
    refs:
      - dev
      - main
      - devops
