services:
  gpu_traefik:
    image: traefik:v2.11
    container_name: gpu_traefik_dev
    command:
      - "--entrypoints.web.address=:8001"
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    ports:
      - "8001:8001"     # Acceso a la app vía Traefik
      - "8080:8080"     # Dashboard (opcional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gpu_traefik_dev

  gpu_full_1:
    image: registry.reputacion.digital/gpu_reports:${IMAGE_VERSION}
    container_name: gpu_full_1
    networks:
      - gpu_traefik_dev
    environment:
      CONFIG_TYPE: "gpu_full_1"
    volumes:
      - ./.env:/app/.env
      - ./models:/app/models
      - ./config.yml:/app/config.yml
    logging:
      driver: gelf
      options:
         gelf-address: "udp://${GELF_IP:-gelf.reputacion.digital}:${GELF_PORT:-12202}"
         tag: ${GELF_TAG}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.full.rule=PathPrefix(`/`)"
      - "traefik.http.routers.full.entrypoints=web"
      - "traefik.http.services.full.loadbalancer.server.port=8002"

networks:
  gpu_traefik_dev:
    driver: bridge
