---
- hosts: "{{ server_name }}"
  vars_files:
    - cred.yml

  tasks:
    - name: log into docker hub registry
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_pswd }}"
        registry_url: "{{ docker_registry }}"

    # # ###############################################################
    # # my_service

    - name: Creates project directory
      file:
        path: /home/operador/{{ folder_name }}
        state: directory
    
    - name: Creates models directory
      file:
        path: /home/operador/{{ folder_name }}/models
        state: directory

    - name: copy_file_docker-compose
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: /home/operador/{{ folder_name }}/docker-compose.yml
        owner: operador
        group: operador
        mode: "0644"

    - name: copy_file_env
      ansible.builtin.copy:
        src: ../.env
        dest: /home/operador/{{ folder_name }}/.env
        owner: operador
        group: operador
        mode: "0644"

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /home/operador/{{ folder_name }}/
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/operador/{{ folder_name }}/
        pull: true
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Run `docker-compose up` again
      community.docker.docker_compose:
        project_src: /home/operador/{{ folder_name }}/
        build: no
      register: output

    - ansible.builtin.debug:
        var: output
# # to call this playbook from the root of the repository:
# # echo $ANSIBLE_VAULT_PASSWORD >  password.txt
# # ansible-playbook -i .ansible/hosts --vault-password-file=password.txt .ansible/docker_remote_launch.yml --extra-vars "server_name=spiderman"
